# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plart
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: 5000
  servlet:
    session:
      timeout: 15m
